#pragma once
// Reverse engineered from Warcraft III binary

#include <cstdint>
#include "StormMac/Handle.h"

// Font handle types
typedef HOBJECT HTEXTFONT;
typedef HOBJECT HTEXTBLOCK;

// Quoted code types for text parsing
enum QUOTEDCODE {
    QUOTEDCODE_NONE = 0,
    QUOTEDCODE_NEWLINE = 1,
    QUOTEDCODE_TAB = 2,
    QUOTEDCODE_COLORON = 3,
    QUOTEDCODE_COLORRESTORE = 4,
    QUOTEDCODE_HYPERLINKSTART = 5,
    QUOTEDCODE_HYPERLINKSTOP = 6,
    QUOTEDCODE_TEXTURESTART = 7,
    QUOTEDCODE_TEXTURESTOP = 8,
};

// Short aliases used throughout font code
#define CODE_INVALIDCODE     QUOTEDCODE_NONE
#define CODE_NEWLINE         QUOTEDCODE_NEWLINE
#define CODE_TAB             QUOTEDCODE_TAB
#define CODE_COLORON         QUOTEDCODE_COLORON
#define CODE_COLORRESTORE    QUOTEDCODE_COLORRESTORE
#define CODE_HYPERLINKSTART  QUOTEDCODE_HYPERLINKSTART
#define CODE_HYPERLINKSTOP   QUOTEDCODE_HYPERLINKSTOP
#define CODE_TEXTURESTART    QUOTEDCODE_TEXTURESTART
#define CODE_TEXTURESTOP     QUOTEDCODE_TEXTURESTOP

